import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const GeneralSans = localFont({
  src: "../../public/assets/GeneralSans-Medium.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeneralSans.className}>{children}</body>
    </html>
  );
}
